version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - ango:ro

  postgres:
    image: kiasaki/alpine-postgres:9.5
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=randomTestPassword

  ango:
    build: .
    container_name: ango
    command: "/src/manage.py test /src/src"
    image: ncrmro/ango
    volumes:
      - /ango/staticfiles
      - ./deps/nginx:/etc/nginx/vhost.d:ro
    ports:
      - "80:8000"
    environment:
      - VIRTUAL_HOST=192.168.99.169
      - VIRTUAL_PORT=8000
      - DJANGO_SETTINGS_MODULE=ango.settings.prod
      - SECRET_KEY='000000000000000'
      - DATABASE_URL=postgres://admin:randomTestPassword@postgres:5432/admin
      - ALLOWED_HOSTS=['*']
    depends_on:
      - postgres
